#!/bin/bash
cython -a match.pyx
clang -shared -pthread -fPIC -fwrapv -O3 -Wall -fno-strict-aliasing \
-I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/Current/include/python2.7/ \
-I/usr/local/lib/python2.7/site-packages/numpy/core/include \
-L/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/Current/lib/ \
-lpython2.7 -o match.so match.c
